### ISSUE TITLE
Membership Issues 

### ISSUE THREAD

**Issue by iskandarCsc** [creative-system-consultant/SISKOPv3#27]
19/2 - pls set share_monthly = 0.00 instead of NULL if share_pmt_mode_flag = 1
20/2 - table approval list of membership - member chose instalment so column share fee supposed to be RM50 rather than RM500. refer this [https://docs.google.com/spreadsheets/d/1AzNKSYcxuP5ed6_-dxTmo9P4li_wmzmV4avTiBuuXEk/edit#gid=1162493970&range=C195](https://github.com/creative-system-consultant/SISKOPv3/issues/new#gid=1162493970&range=C195)

**Comment by nazirulfitrifauzi** [comment]
Resolved with PR #26
