### ISSUE TITLE
Membership Approval Issues

### ISSUE THREAD

**Issue by iskandarCsc** [creative-system-consultant/SISKOPv3#30]
19/2 - btn suggest decline by maker should not be approved yet if there are other level approval. supposed to send application to checker and approver. application should be approved by approver role only."

"22/2 - after enter notes/ comment in approval at (maker,checker)- text in the field race gender and marital changed to another text
refer this :

[https://docs.google.com/spreadsheets/d/1AzNKSYcxuP5ed6_-dxTmo9P4li_wmzmV4avTiBuuXEk/edit#gid=1162493970&range=C270](https://github.com/creative-system-consultant/SISKOPv3/issues/new#gid=1162493970&range=C270)"

**Comment by nazirulfitrifauzi** [comment]
Resolved with PR #31
