### ISSUE TITLE
Application List Fixes

### ISSUE THREAD

**Issue by iskandarCsc** [creative-system-consultant/SISKOPv3#32]
"22/2 - apply_date at  list of add contribution should pull from apply date not created at date
please check at add share,withdraw contribution, sell/exchange, special aid, dividen withdraw and close memebrship too

refer table siskop.contribution at column apply_date 
etc. user (farahin) 
[https://docs.google.com/spreadsheets/d/1AzNKSYcxuP5ed6_-dxTmo9P4li_wmzmV4avTiBuuXEk/edit#gid=1162493970&range=C380](https://github.com/creative-system-consultant/SISKOPv3/issues/new#gid=1162493970&range=C380) "

This issue also exists for other applications.

**Comment by nazirulfitrifauzi** [comment]
Resolved with PR #33
