### ISSUE TITLE
Dividend Application and Approval Bugs

### ISSUE THREAD

**Issue by iskandarCsc** [creative-system-consultant/SISKOPv3#47]
20/2 : at field (current balance dividen) , amount bal_dividen - bal_div_pending_withdrawal
"27/2 - default amount withdraw  to 0 instead of taking the amount that the user previously approved
"8/2
- pegawai(maker) - x boleh masukkan amount approved if amount applied = 0 
- tmbh validation dkt amount approved (cash,share,contribution) maker hanya boleh masukkan amount kurang daripada amount applied 
- default amount for approve amount field at maker should follow amt applied."

**Comment by nazirulfitrifauzi** [comment]
Resolved with PR #48
