### ISSUE TITLE
Misc All Approver Fixes

### ISSUE THREAD

**Issue by iskandarCsc** [creative-system-consultant/SISKOPv3#53]
"28/2
1. approver - clearance date reduce 1 day each time insert comment in text box
2. to be discuss - what should be happen to approver clearance cheque date if maker decline the approval without choose any clearance cheque date"

"28/2 - add validation for cheque clearance date  (method-payonce(cheque))
rule :
1. cheque clear date >= cheque date                
2. cheque clearance date <= current date                
"
"28/2 - add validation for cheque clearance date 
rule :
1. cheque clear date >= cheque date                
2. cheque clearance date <= current date                
"
"8/2
- maker approval - if amt applied in cash, share, cont  = 0, maker should be cannot insert any value in amt approved.
- maker approval - to add validation to amt approved - maker only can insert value =< amt applied 
- default amount for approve amount field at maker should follow amt applied.

**Comment by nazirulfitrifauzi** [comment]
Resolved with PR #54
