### ISSUE TITLE
Select Client Bug

### ISSUE THREAD

**Issue by iskandarCsc** [creative-system-consultant/SISKOPv3#9]
UUID COLUMN REMOVED

**Comment by nazirulfitrifauzi** [comment]
Temporary solution with PR #10 . 

Changed to use ID instead of UUID. Need to add UUID data back @iskandarCsc @hafidzcsc @yanabudi96

**Comment by nazirulfitrifauzi** [comment]
Latest PR #36 has been revert to use UUID back instead of ID. Issue closed! khalas
